name: GitHub Actions Demo

permissions: read-all

env: 
  GLOBAL_VAR: GlobalValue

concurrency: 
  group: mygroup

run-name: this is my run name

defaults:
  run:
    shell: bash
    # working-directory: /
  
on:
  push:
    branches: 
    - main
#    paths-ignore: .github/**

  pull_request:
    branches: main
    
  # schedule:
  #   - cron: "15 6 * * 0"
     
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment'
        type: environment
        required: true

jobs:

  Logs:
    runs-on: ubuntu-latest
    steps: 
      - run: |
          echo "Writing to the logs"
          echo "::group::writing to the log"
          echo "::debug file=myfile,line=5,endLine=10,title=my error::the error message"
          echo "::notice file=myfile,line=5,endLine=10,title=my error::the error message"
          echo "::warning file=myfile,line=5,endLine=10,title=my error::the error message"
          echo "::error file=myfile,line=5,endLine=10,title=my error::the error message"
          echo "::endgroup::"
        continue-on-error: true  

      - run: echo "statevar=stateval" >> "$GITHUB_STATE"

      - run: echo "outputvar=outputval" >> "$GITHUB_OUTPUT"
        id: output-step

      - run: echo "${{ steps.output-step.outputs.outputvar }}"
      
  DumpContext:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(runner) }}'
      - run: echo '${{ toJSON(github) }}'
      - env: 
          testEnv: MyEnvVar
        run: echo '${{ toJSON(env) }}'
      - run: echo '${{ toJSON(matrix) }}'

      
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: output event
        shell: bash                                  # bash, pwsh, python, cmd, powershell
        run: echo ${{ github.event_name }}
        working-directory: /tmp
        continue-on-error: true
        timeout-minutes: 10
    

      - name: python 
        shell: python
        run: |
          import platform
          print(platform.platform())

      - name: output branch
        run: echo ${{ github.ref }}

      - uses: actions/checkout@v4.1.1

      - name: list files
        run: tree


  Test:
    runs-on: ubuntu-latest
    environment: Test
    needs: Build
    if: github.event_name == 'workflow_dispatch'
    steps:
      - run: echo Testing
    
  LoadTest:
    runs-on: ubuntu-latest
    environment: Load-Test
    needs: Build
    if: github.event_name == 'workflow_dispatch'
    steps:
      - run: | 
          echo Testing
          sleep 15

   
  Production:
    runs-on: ubuntu-latest
    environment: Production
    needs: 
      - Test
      - LoadTest
    if: github.event.inputs.environment == 'Production'
    steps:
      - run: | 
          echo "Step 1"
          sleep 10
      - run: | 
          echo "Step 2"
          sleep 10
      - run: | 
          echo "Step 3"
          sleep 10
      - run: | 
          echo "Step 4"
          sleep 10
      - run: | 
          echo "Step 5"
          sleep 10


          
  
