name: GitHub Actions Demo

permissions: read-all

env: 
  GLOBAL_VAR: GlobalValue

concurrency: 
  group: mygroup

run-name: this is my run name

defaults:
  run:
    shell: bash
    # working-directory: /
  
on:
  push:
    branches: 
    - main
#    paths-ignore: .github/**

  pull_request:
    branches: main
    
  # schedule:
  #   - cron: "15 6 * * 0"
     
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment'
        type: environment
        required: true

jobs:

  Logs:
    runs-on: ubuntu-latest
    steps: 
      - run: |
          echo "Writing to the logs"
          echo "::group::writing to the log"
          echo "::debug file=myfile,line=5,endLine=10,title=my error::the error message"
          echo "::notice file=myfile,line=5,endLine=10,title=my error::the error message"
          echo "::warning file=myfile,line=5,endLine=10,title=my error::the error message"
          echo "::error file=myfile,line=5,endLine=10,title=my error::the error message"
          echo "::endgroup::"
        continue-on-error: true  

      - run: echo "statevar=stateval" >> "$GITHUB_STATE"

      - run: echo "outputvar=outputval" >> "$GITHUB_OUTPUT"
        id: output-step

      - run: echo "${{ steps.output-step.outputs.outputvar }}"

      - run: echo "into the step summary :rocket:" >> "$GITHUB_STEP_SUMMARY"

      - run: echo "MY_OWN_SECRET=${{ secrets.MY_OWN_SECRET }}"

      - run: |
          echo "${{ secrets.MY_OWN_SECRET }}" >> secret.txt
          cat secret.txt

      - run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"

  DumpContext:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(runner) }}'
      - run: echo '${{ toJSON(github) }}'
      - env: 
          testEnv: MyEnvVar
        run: echo '${{ toJSON(env) }}'
      - run: echo '${{ toJSON(matrix) }}'


  Cache:
    runs-on: ubuntu-latest
    steps:
      - name: setup cache
        id: setup-cache
        uses: actions/cache@v3
        with:
          path: cachefile
          key: ${{ runner.os }}-cachefile

      - name: write cache
        if: steps.setup-cache.outputs.cache-hit != 'true'
        run: echo mydataaaaa >> cachefile

      - name: cache read
        run: cat cachefile

  Build:
    runs-on: ubuntu-latest
    steps:
      - name: output event
        shell: bash                                  # bash, pwsh, python, cmd, powershell
        run: echo ${{ github.event_name }}
        working-directory: /tmp
        continue-on-error: true
        timeout-minutes: 10
    

      - name: python 
        shell: python
        run: |
          import platform
          print(platform.platform())

      - name: output branch
        run: echo ${{ github.ref }}

      - uses: actions/checkout@v4.1.1

      - name: list files
        run: tree

      - run: echo "more info added to the step summary :rocket:" >> "$GITHUB_STEP_SUMMARY"


  Test:
    runs-on: ubuntu-latest
    environment: Test
    needs: Build
    if: github.event_name == 'workflow_dispatch'
    steps:
      - run: echo Testing
    
  LoadTest:
    runs-on: ubuntu-latest
    environment: Load-Test
    needs: Build
    if: github.event_name == 'workflow_dispatch'

    strategy:
      matrix: 
        os:
          - win
          - linux
        jvm:
          - jdk7
          - jkd8
    
    steps:
      - name: Testing ${{ matrix.os }} on ${{ matrix.os }}
        run: | 
          echo "Testing ${{ matrix.os }} on ${{ matrix.os }}"
          echo "Testing ${{ matrix.os }} on ${{ matrix.os }} :check:" >> "$GITHUB_STEP_SUMMARY"
          sleep 5

   
  Production:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://github.com
    needs: 
      - Test
      - LoadTest
    if: github.event.inputs.environment == 'Production'
    steps:
      - run: | 
          echo "Step 1"
          sleep 10
      - run: | 
          echo "Step 2"
          sleep 10
      - run: | 
          echo "Step 3"
          sleep 10
      - run: | 
          echo "Step 4"
          sleep 10
      - run: | 
          echo "Step 5"
          sleep 10


          
  
