
name: Reuse other workflow

on: 
  workflow_dispatch:

jobs:
  call-workflow:
    uses: .github/workflows/reusable.yml@main
    with:
      who-to-great: "Paul"

  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
     - run: echo "Time ${{ needs.call-workflow.outputs.current-time }}"
    
    
